/* =========================================================
   ALHERO — STORY POLISH
   Chapter 2: pacing + suspense pass
   This file overrides only the chapter text; the original data remains intact.
========================================================= */

(() => {
    const chapters = window.ALHERO_CHAPTERS;
    if (!Array.isArray(chapters) || !chapters[1]) return;

    chapters[1].ar = {
        title: "من البداية",
        paragraphs: [
            "استيقظ ألهيرو قبل شروق الشمس.",
            "لثوانٍ، نسي أين هو.",
            "لا بالدونز. لا القصر. لا أصوات الفرسان.",
            "فقط الرياح... وصوت رايفن من خلفه.",
            "\"صحيت؟\"",
            "التفت ألهيرو، فوجد رايفن واقفًا أمام الكوخ وسيفين خشبيين في يده.",
            "\"أمسك واحدًا.\"",
            "أخذ ألهيرو السيف.",
            "\"هنبدأ التدريب؟\"",
            "ابتسم رايفن.",
            "\"لا. النهارده هتتعلم حاجة أهم.\"",
            "أشار إلى الغابة.",
            "\"هتتعلم تشوف... قبل ما تضرب.\"",
            "دخل ألهيرو الغابة وحده.",
            "في البداية لم يجد شيئًا غريبًا.",
            "ثم سمع خطوة خلفه.",
            "استدار فورًا.",
            "لا أحد.",
            "خطوة أخرى من الجهة المقابلة.",
            "وضع يده على سيفه.",
            "وفجأة ظهر رايفن أمامه.",
            "\"كنت هتضرب مين؟\"",
            "\"اللي كان ورايا.\"",
            "هز رايفن رأسه.",
            "\"أنت سمعت الصوت... لكنك ما شفتش اللي سببه.\"",
            "ثم اختفى بين الأشجار.",
            "وقف ألهيرو مكانه.",
            "هذه المرة لم يتحرك.",
            "أغلق عينيه، واستمع.",
            "رياح من اليمين.",
            "غصن مكسور من اليسار.",
            "ونَفَس قريب جدًا منه.",
            "فتح عينيه، لكنه لم يهاجم.",
            "قال بهدوء: \"رايفن... أنت ورايا.\"",
            "ضحك رايفن من بين الأشجار.",
            "\"أخيرًا بدأت تشوف.\"",
            "قبل أن يغادر ألهيرو الغابة، لمح شيئًا محفورًا على جذع شجرة.",
            "علامة سوداء صغيرة... دائرة يتوسطها خط مائل.",
            "مد يده نحوها.",
            "لكن رايفن أمسك معصمه فورًا.",
            "\"ما تلمسهاش.\"",
            "نظر ألهيرو إليه باستغراب.",
            "\"إيه دي؟\"",
            "سكت رايفن لحظة.",
            "ثم قال: \"علامة قديمة. انساها.\"",
            "لكن ألهيرو لاحظ شيئًا واحدًا.",
            "رايفن لم ينظر إلى العلامة... بل نظر حوله، كأنه يتأكد أن أحدًا لم يرهما.",
            "---",
            "مرت الأسابيع.",
            "لم يعد التدريب مجرد ضربات وسرعة.",
            "كان رايفن يضع ألهيرو في مواقف تجبره على الاختيار: يهاجم أم ينتظر؟ يطارد أم ينسحب؟ يثق أم يشك؟",
            "وببطء، بدأ ألهيرو يتغير.",
            "لم يعد أول شيء يفعله هو سحب سيفه.",
            "وفي صباح أحد الأيام، وضع رايفن خريطة على الطاولة.",
            "\"اختبارك الحقيقي بدأ.\"",
            "نظر ألهيرو إلى الخريطة.",
            "قرية صغيرة في الشمال.",
            "ثلاثة رجال مسلحين سيطروا عليها.",
            "\"عايزني أخرجهم؟\"",
            "\"عايزك تنقذ أهل القرية... من غير ما تقتل حد.\"",
            "ابتسم ألهيرو.",
            "\"أقدر.\"",
            "هذه المرة لم يصححه رايفن.",
            "فقط قال: \"ارجعلي وأنت متأكد إنك فاهم ليه نجحت.\"",
            "---",
            "وصل ألهيرو إلى القرية قبل الغروب.",
            "وكان أول شيء شعر به هو الصمت.",
            "لا أطفال.",
            "لا أبواب مفتوحة.",
            "ولا حتى نباح كلاب.",
            "في وسط القرية وقف ثلاثة رجال مسلحين.",
            "لكن شيئًا فيهم لم يعجب ألهيرو.",
            "لم يكونوا يتصرفون كقطاع طرق.",
            "كانوا ينتظرون شخصًا.",
            "رفع أحدهم رأسه عندما رأى ألهيرو.",
            "\"إنت مين؟\"",
            "أجاب ألهيرو: \"الشخص اللي هيخليكم تمشوا من هنا.\"",
            "ضحك الرجل وسحب سيفه.",
            "\"لوحدك؟\"",
            "قال ألهيرو: \"يكفي.\"",
            "اندفع الرجل.",
            "انتظر ألهيرو حتى اللحظة الأخيرة، ثم تفادى الضربة وأسقط سيفه.",
            "هجم الثاني، فأسقط سلاحه بضربة واحدة.",
            "أما الثالث فتراجع خطوة.",
            "ثم قال شيئًا جعل ألهيرو يتوقف.",
            "\"إنت... ألهيرو؟\"",
            "تغيرت ملامح ألهيرو.",
            "\"إنت تعرف اسمي؟\"",
            "الرجل لم يجب.",
            "رفع ألهيرو عينيه إلى يده.",
            "كانت نفس العلامة السوداء محفورة على معصمه.",
            "الدائرة... والخط المائل.",
            "قال ألهيرو: \"مين بعتكم؟\"",
            "الرجل ابتسم رغم خوفه.",
            "\"إحنا مش هنا عشانك.\"",
            "توقف لحظة.",
            "\"إحنا هنا عشان نتأكد إنك لسه حي.\"",
            "ساد الصمت.",
            "ألهيرو لم يفهم.",
            "لكن الرجل رفع سيفه مرة أخرى.",
            "هذه المرة لم يسمح له ألهيرو بالهجوم.",
            "أسقطه بسرعة، ثم قال للثلاثة:",
            "\"انتهى الأمر. اخرجوا.\"",
            "نظروا إليه، ثم تركوا أسلحتهم.",
            "لم يقتل أحدًا.",
            "لكنه خرج من القرية ومعه سؤال أخطر من أي معركة خاضها.",
            "من كان يعرف أنه حي؟",
            "---",
            "عاد ألهيرو إلى الكوخ بعد الغروب.",
            "كان رايفن ينتظره.",
            "قبل أن يسأله عن الاختبار، قال ألهيرو:",
            "\"إنت كنت عارف.\"",
            "توقف رايفن.",
            "\"عارف إيه؟\"",
            "ألهيرو أخرج السيف الخشبي من يده ووضعه على الطاولة.",
            "\"العلامة.\"",
            "ظل رايفن صامتًا.",
            "ثم قال: \"احكيلي اللي حصل.\"",
            "ألهيرو حكى كل شيء.",
            "وعندما وصل إلى الجملة: \"إحنا هنا عشان نتأكد إنك لسه حي\"، تغير وجه رايفن.",
            "لأول مرة منذ عرفه ألهيرو، بدا عليه الخوف.",
            "قال ألهيرو: \"مين دول؟\"",
            "رايفن لم يجب.",
            "بدلًا من ذلك، نظر إلى الطريق خلف ألهيرو.",
            "ومن بعيد... سمع الاثنان صوت حوافر حصان.",
            "اقترب الصوت بسرعة.",
            "ظهر فارس يحمل راية بالدونز.",
            "تجمد ألهيرو.",
            "أما رايفن، فتنفس ببطء وقال:",
            "\"كنت أتمنى إن اليوم ده ما يجيش.\"",
            "اقترب الفارس حتى توقف أمام الكوخ.",
            "نزل من على حصانه.",
            "نظر إلى رايفن... ثم إلى ألهيرو.",
            "وقال بصوت واضح:",
            "\"ألهيرو؟\"",
            "لم يجب ألهيرو.",
            "لأن رايفن قال جملة واحدة قبل أن يتحرك:",
            "\"الماضي ما رجعش عشان ياخدك... رجع عشان يكشف مين كان بيحركه من البداية.\"",
            "نهاية الفصل الثاني."
        ]
    };

    window.ALHERO_ENGLISH_CHAPTERS = window.ALHERO_ENGLISH_CHAPTERS || [];
    window.ALHERO_ENGLISH_CHAPTERS[1] = {
        title: "From the Beginning",
        paragraphs: [
            "Alhero woke before sunrise.",
            "For a few seconds, he forgot where he was.",
            "No Baldons. No palace. No knights.",
            "Only the wind... and Raven's voice behind him.",
            "\"Awake?\"",
            "Alhero turned and found Raven standing outside the hut with two wooden swords.",
            "\"Take one.\"",
            "Alhero took the sword.",
            "\"Training?\"",
            "Raven smiled.",
            "\"No. Today you're learning something more important.\"",
            "He pointed toward the forest.",
            "\"You're going to learn how to see... before you strike.\"",
            "Alhero entered the forest alone.",
            "At first, nothing seemed strange.",
            "Then he heard a step behind him.",
            "He turned immediately.",
            "No one.",
            "Another step came from the opposite direction.",
            "His hand moved toward his sword.",
            "Raven suddenly appeared in front of him.",
            "\"Who were you going to strike?\"",
            "\"Whoever was behind me.\"",
            "Raven shook his head.",
            "\"You heard the sound... but you never saw what caused it.\"",
            "Then he disappeared between the trees.",
            "Alhero stayed still.",
            "This time, he did not move.",
            "He closed his eyes and listened.",
            "Wind to the right.",
            "A broken branch to the left.",
            "And breathing very close to him.",
            "He opened his eyes, but did not attack.",
            "\"Raven... you're behind me.\"",
            "Raven laughed from between the trees.",
            "\"You're finally starting to see.\"",
            "Before leaving the forest, Alhero noticed something carved into a tree.",
            "A small black mark... a circle crossed by a single line.",
            "He reached toward it.",
            "Raven immediately caught his wrist.",
            "\"Don't touch it.\"",
            "Alhero looked at him.",
            "\"What is it?\"",
            "Raven was silent for a moment.",
            "\"An old mark. Forget it.\"",
            "But Alhero noticed one thing.",
            "Raven did not look at the mark. He looked around, as if making sure no one had seen them.",
            "---",
            "Weeks passed.",
            "Training was no longer just about strikes and speed.",
            "Raven forced Alhero to choose: attack or wait, chase or retreat, trust or doubt.",
            "Slowly, Alhero changed.",
            "He no longer reached for his sword first.",
            "One morning, Raven placed a map on the table.",
            "\"Your real test begins.\"",
            "A small village lay to the north.",
            "Three armed men had taken control of it.",
            "\"You want me to remove them?\"",
            "\"I want you to save the villagers without killing anyone.\"",
            "Alhero smiled.",
            "\"I can do it.\"",
            "This time Raven did not correct him.",
            "He only said, \"Come back knowing why you succeeded.\"",
            "---",
            "Alhero reached the village before sunset.",
            "The first thing he noticed was the silence.",
            "No children.",
            "No open doors.",
            "Not even barking dogs.",
            "Three armed men stood in the center of the village.",
            "But something about them felt wrong.",
            "They did not act like common bandits.",
            "They were waiting for someone.",
            "One of them looked up when he saw Alhero.",
            "\"Who are you?\"",
            "Alhero answered, \"The person who's going to make you leave.\"",
            "The man laughed and drew his sword.",
            "\"Alone?\"",
            "\"Enough.\"",
            "The man charged.",
            "Alhero waited until the last moment, then dodged and knocked the sword away.",
            "The second attacked. Alhero disarmed him with one strike.",
            "The third stepped back.",
            "Then he said something that made Alhero stop.",
            "\"You... you're Alhero?\"",
            "Alhero's expression changed.",
            "\"You know my name?\"",
            "The man said nothing.",
            "Alhero looked at his hand.",
            "The same black mark was carved into his wrist.",
            "The circle... and the line through it.",
            "Alhero asked, \"Who sent you?\"",
            "The man smiled despite his fear.",
            "\"We're not here for you.\"",
            "He paused.",
            "\"We're here to make sure you're still alive.\"",
            "Silence filled the village.",
            "Alhero did not understand.",
            "The man raised his sword again.",
            "This time Alhero did not let him attack.",
            "He disarmed all three and said, \"It's over. Leave.\"",
            "They dropped their weapons.",
            "No one was killed.",
            "But Alhero left with a question more dangerous than any battle: Who knew he was alive?",
            "---",
            "Alhero returned to the hut after sunset.",
            "Raven was waiting.",
            "Before Raven could ask about the test, Alhero said, \"You knew.\"",
            "Raven stopped.",
            "\"Knew what?\"",
            "Alhero placed the wooden sword on the table.",
            "\"The mark.\"",
            "Raven remained silent.",
            "Then he said, \"Tell me what happened.\"",
            "Alhero told him everything.",
            "When he repeated, \"We're here to make sure you're still alive,\" Raven's expression changed.",
            "For the first time since Alhero had met him, Raven looked afraid.",
            "Alhero asked, \"Who are they?\"",
            "Raven did not answer.",
            "Instead, he looked toward the road behind Alhero.",
            "In the distance... they heard a horse approaching.",
            "The sound grew louder.",
            "A rider carrying the banner of Baldons appeared.",
            "Alhero froze.",
            "Raven breathed slowly and said, \"I hoped this day would never come.\"",
            "The rider stopped in front of the hut.",
            "He looked at Raven... then at Alhero.",
            "\"Alhero?\"",
            "Alhero did not answer.",
            "Because Raven spoke one sentence first:",
            "\"The past didn't return to take you... it returned to reveal who was moving it from the beginning.\"",
            "End of Chapter Two."
        ]
    };
})();
